/* THIS FILE GENERATED BY bcd.gen */
module sys.x11.Xrender;
import sys.x11.Xlib;
extern(C):
align(4):
const int PictStandardARGB32 = 0;
const int PictStandardRGB24 = 1;
const int PictStandardA8 = 2;
const int PictStandardA4 = 3;
const int PictStandardA1 = 4;
const int PictStandardNUM = 5;
alias _XConicalGradient XConicalGradient;
alias _XPointFixed XPointFixed;
alias int XFixed;
alias _XRadialGradient XRadialGradient;
alias _XCircle XCircle;
alias _XLinearGradient XLinearGradient;
alias _XTrap XTrap;
alias _XSpanFix XSpanFix;
alias _XAnimCursor XAnimCursor;
alias _XIndexValue XIndexValue;
alias _XFilters XFilters;
alias _XTransform XTransform;
alias _XTrapezoid XTrapezoid;
alias _XLineFixed XLineFixed;
alias _XTriangle XTriangle;
alias _XPointDouble XPointDouble;
alias double XDouble;
alias _XGlyphElt32 XGlyphElt32;
alias _XGlyphElt16 XGlyphElt16;
alias _XGlyphElt8 XGlyphElt8;
alias _XGlyphInfo XGlyphInfo;
alias _XRenderPictureAttributes XRenderPictureAttributes;
extern (C) size_t XRenderCreateConicalGradient(void *, _XConicalGradient *, int *, XRenderColor *, int);
extern (C) size_t XRenderCreateRadialGradient(void *, _XRadialGradient *, int *, XRenderColor *, int);
extern (C) size_t XRenderCreateLinearGradient(void *, _XLinearGradient *, int *, XRenderColor *, int);
extern (C) size_t XRenderCreateSolidFill(void *, XRenderColor *);
extern (C) void XRenderAddTraps(void *, size_t, int, int, _XTrap *, int);
extern (C) size_t XRenderCreateAnimCursor(void *, int, _XAnimCursor *);
extern (C) void XRenderSetPictureFilter(void *, size_t, char *, int *, int);
extern (C) _XFilters * XRenderQueryFilters(void *, size_t);
extern (C) size_t XRenderCreateCursor(void *, size_t, size_t, size_t);
extern (C) int XRenderParseColor(void *, char *, XRenderColor *);
extern (C) void XRenderCompositeDoublePoly(void *, int, size_t, size_t, XRenderPictFormat *, int, int, int, int, _XPointDouble *, int, int);
extern (C) void XRenderCompositeTriFan(void *, int, size_t, size_t, XRenderPictFormat *, int, int, _XPointFixed *, int);
extern (C) void XRenderCompositeTriStrip(void *, int, size_t, size_t, XRenderPictFormat *, int, int, _XPointFixed *, int);
extern (C) void XRenderCompositeTriangles(void *, int, size_t, size_t, XRenderPictFormat *, int, int, _XTriangle *, int);
extern (C) void XRenderCompositeTrapezoids(void *, int, size_t, size_t, XRenderPictFormat *, int, int, _XTrapezoid *, int);
extern (C) void XRenderFillRectangles(void *, int, size_t, XRenderColor *, XRectangle *, int);
extern (C) void XRenderFillRectangle(void *, int, size_t, XRenderColor *, int, int, size_t, size_t);
extern (C) void XRenderCompositeText32(void *, int, size_t, size_t, XRenderPictFormat *, int, int, int, int, _XGlyphElt32 *, int);
extern (C) void XRenderCompositeText16(void *, int, size_t, size_t, XRenderPictFormat *, int, int, int, int, _XGlyphElt16 *, int);
extern (C) void XRenderCompositeText8(void *, int, size_t, size_t, XRenderPictFormat *, int, int, int, int, _XGlyphElt8 *, int);
extern (C) void XRenderCompositeString32(void *, int, size_t, size_t, XRenderPictFormat *, size_t, int, int, int, int, size_t *, int);
extern (C) void XRenderCompositeString16(void *, int, size_t, size_t, XRenderPictFormat *, size_t, int, int, int, int, ushort *, int);
extern (C) void XRenderCompositeString8(void *, int, size_t, size_t, XRenderPictFormat *, size_t, int, int, int, int, char *, int);
extern (C) void XRenderFreeGlyphs(void *, size_t, size_t *, int);
extern (C) void XRenderAddGlyphs(void *, size_t, size_t *, _XGlyphInfo *, int, char *, int);
extern (C) void XRenderFreeGlyphSet(void *, size_t);
extern (C) size_t XRenderReferenceGlyphSet(void *, size_t);
extern (C) size_t XRenderCreateGlyphSet(void *, XRenderPictFormat *);
extern (C) void XRenderComposite(void *, int, size_t, size_t, size_t, int, int, int, int, int, int, size_t, size_t);
extern (C) void XRenderFreePicture(void *, size_t);
extern (C) void XRenderSetPictureTransform(void *, size_t, _XTransform *);
extern (C) void XRenderSetPictureClipRegion(void *, size_t, void *);
extern (C) void XRenderSetPictureClipRectangles(void *, size_t, int, int, XRectangle *, int);
extern (C) void XRenderChangePicture(void *, size_t, size_t, _XRenderPictureAttributes *);
extern (C) size_t XRenderCreatePicture(void *, size_t, XRenderPictFormat *, size_t, _XRenderPictureAttributes *);
extern (C) _XIndexValue * XRenderQueryPictIndexValues(void *, XRenderPictFormat *, int *);
extern (C) XRenderPictFormat * XRenderFindStandardFormat(void *, int);
extern (C) XRenderPictFormat * XRenderFindFormat(void *, size_t, XRenderPictFormat *, int);
extern (C) XRenderPictFormat * XRenderFindVisualFormat(void *, Visual *);
extern (C) int XRenderSetSubpixelOrder(void *, int, int);
extern (C) int XRenderQuerySubpixelOrder(void *, int);
extern (C) int XRenderQueryFormats(void *);
extern (C) int XRenderQueryVersion(void *, int *, int *);
extern (C) int XRenderQueryExtension(void *, int *, int *);
alias void function(void *, char *, int, int, char * *) _BCD_func__1290;
alias int function(void *) _BCD_func__1332;
alias int function(void *, XErrorEvent *) _BCD_func__1333;
alias void function(void *, char *, char *) _BCD_func__1406;
alias int function(void *, char *, char *) _BCD_func__1407;
alias void function(void *, char *, char *) _BCD_func__1408;
struct _XConicalGradient {
_XPointFixed center;
int angle;
}
struct _XRadialGradient {
_XCircle inner;
_XCircle outer;
}
struct _XLinearGradient {
_XPointFixed p1;
_XPointFixed p2;
}
struct _XTrap {
_XSpanFix top;
_XSpanFix bottom;
}
struct _XSpanFix {
int left;
int right;
int y;
}
struct _XAnimCursor {
size_t cursor;
size_t delay;
}
struct _XIndexValue {
size_t pixel;
ushort red;
ushort green;
ushort blue;
ushort alpha;
}
struct _XFilters {
int nfilter;
char * * filter;
int nalias;
short * alias_;
}
struct _XTransform {
int [3] [3] matrix;
}
struct _XTrapezoid {
int top;
int bottom;
_XLineFixed left;
_XLineFixed right;
}
struct _XCircle {
int x;
int y;
int radius;
}
struct _XTriangle {
_XPointFixed p1;
_XPointFixed p2;
_XPointFixed p3;
}
struct _XLineFixed {
_XPointFixed p1;
_XPointFixed p2;
}
struct _XPointFixed {
int x;
int y;
}
struct _XPointDouble {
double x;
double y;
}
struct _XGlyphElt32 {
size_t glyphset;
size_t * chars;
int nchars;
int xOff;
int yOff;
}
struct _XGlyphElt16 {
size_t glyphset;
ushort * chars;
int nchars;
int xOff;
int yOff;
}
struct _XGlyphElt8 {
size_t glyphset;
char * chars;
int nchars;
int xOff;
int yOff;
}
struct _XGlyphInfo {
ushort width;
ushort height;
short x;
short y;
short xOff;
short yOff;
}
struct XRenderColor {
ushort red;
ushort green;
ushort blue;
ushort alpha;
}
struct _XRenderPictureAttributes {
int repeat;
size_t alpha_map;
int alpha_x_origin;
int alpha_y_origin;
int clip_x_origin;
int clip_y_origin;
size_t clip_mask;
int graphics_exposures;
int subwindow_mode;
int poly_edge;
int poly_mode;
size_t dither;
int component_alpha;
}
struct XRenderPictFormat {
size_t id;
int type;
int depth;
XRenderDirectFormat direct;
size_t colormap;
}
struct XRenderDirectFormat {
short red;
short redMask;
short green;
short greenMask;
short blue;
short blueMask;
short alpha;
short alphaMask;
}
