/* THIS FILE GENERATED BY bcd.gen */
module sys.x11.Xutil;
import sys.x11.Xlib;
align(4):
const int NoValue = 0x0000;
const int XValue = 0x0001;
const int YValue = 0x0002;
const int WidthValue = 0x0004;
const int HeightValue = 0x0008;
const int AllValues = 0x000F;
const int XNegative = 0x0010;
const int YNegative = 0x0020;
const int WithdrawnState = 0;
const int NormalState = 1;
const int IconicState = 3;
const int DontCareState = 0;
const int ZoomState = 2;
const int InactiveState = 4;
const int XNoMemory = -1;
const int XLocaleNotSupported = -2;
const int XConverterNotFound = -3;
const int RectangleOut = 0;
const int RectangleIn = 1;
const int RectanglePart = 2;
const int VisualNoMask = 0x0;
const int VisualIDMask = 0x1;
const int VisualScreenMask = 0x2;
const int VisualDepthMask = 0x4;
const int VisualClassMask = 0x8;
const int VisualRedMaskMask = 0x10;
const int VisualGreenMaskMask = 0x20;
const int VisualBlueMaskMask = 0x40;
const int VisualColormapSizeMask = 0x80;
const int VisualBitsPerRGBMask = 0x100;
const int VisualAllMask = 0x1FF;
const int BitmapSuccess = 0;
const int BitmapOpenFailed = 1;
const int BitmapFileInvalid = 2;
const int BitmapNoMemory = 3;
const int XCSUCCESS = 0;
const int XCNOMEM = 1;
const int XCNOENT = 2;
alias int XContext;
alias void * Region;
alias _XComposeStatus XComposeStatus;
enum XICCEncodingStyle {
XStringStyle=0,
XCompoundTextStyle=1,
XTextStyle=2,
XStdICCTextStyle=3,
XUTF8StringStyle=4,
}
extern (C) int XXorRegion(void *, void *, void *);
extern (C) int XWMGeometry(void *, int, char *, char *, uint, XSizeHints *, int *, int *, int *, int *, int *);
extern (C) int XUnionRegion(void *, void *, void *);
extern (C) int XUnionRectWithRegion(XRectangle *, void *, void *);
extern (C) int Xutf8TextPropertyToTextList(void *, XTextProperty *, char * * *, int *);
extern (C) int XwcTextPropertyToTextList(void *, XTextProperty *, wchar * * *, int *);
extern (C) int XmbTextPropertyToTextList(void *, XTextProperty *, char * * *, int *);
extern (C) int XTextPropertyToStringList(XTextProperty *, char * * *, int *);
extern (C) void XwcFreeStringList(wchar * *);
extern (C) int Xutf8TextListToTextProperty(void *, char * *, int, int, XTextProperty *);
extern (C) int XwcTextListToTextProperty(void *, wchar * *, int, int, XTextProperty *);
extern (C) int XmbTextListToTextProperty(void *, char * *, int, int, XTextProperty *);
extern (C) int XSubtractRegion(void *, void *, void *);
extern (C) int XStringListToTextProperty(char * *, int, XTextProperty *);
extern (C) int XShrinkRegion(void *, int, int);
extern (C) int XSetZoomHints(void *, size_t, XSizeHints *);
extern (C) void XSetStandardColormap(void *, size_t, XStandardColormap *, size_t);
extern (C) int XSetRegion(void *, void *, void *);
extern (C) void XSetWMSizeHints(void *, size_t, XSizeHints *, size_t);
extern (C) void Xutf8SetWMProperties(void *, size_t, char *, char *, char * *, int, XSizeHints *, XWMHints *, XClassHint *);
extern (C) void XmbSetWMProperties(void *, size_t, char *, char *, char * *, int, XSizeHints *, XWMHints *, XClassHint *);
extern (C) void XSetWMProperties(void *, size_t, XTextProperty *, XTextProperty *, char * *, int, XSizeHints *, XWMHints *, XClassHint *);
extern (C) void XSetWMNormalHints(void *, size_t, XSizeHints *);
extern (C) void XSetWMName(void *, size_t, XTextProperty *);
extern (C) void XSetWMIconName(void *, size_t, XTextProperty *);
extern (C) int XSetWMHints(void *, size_t, XWMHints *);
extern (C) void XSetWMClientMachine(void *, size_t, XTextProperty *);
extern (C) void XSetTextProperty(void *, size_t, XTextProperty *, size_t);
extern (C) int XSetStandardProperties(void *, size_t, char *, char *, size_t, char * *, int, XSizeHints *);
extern (C) int XSetSizeHints(void *, size_t, XSizeHints *, size_t);
extern (C) void XSetRGBColormaps(void *, size_t, XStandardColormap *, int, size_t);
extern (C) int XSetNormalHints(void *, size_t, XSizeHints *);
extern (C) int XSetIconSizes(void *, size_t, XIconSize *, int);
extern (C) int XSetClassHint(void *, size_t, XClassHint *);
extern (C) int XSaveContext(void *, size_t, int, char *);
extern (C) int XRectInRegion(void *, int, int, uint, uint);
extern (C) void * XPolygonRegion(XPoint *, int, int);
extern (C) int XPointInRegion(void *, int, int);
extern (C) int XOffsetRegion(void *, int, int);
extern (C) int XMatchVisualInfo(void *, int, int, int, XVisualInfo *);
extern (C) int XLookupString(XKeyEvent *, char *, int, size_t *, _XComposeStatus *);
extern (C) void XConvertCase(size_t, size_t *, size_t *);
extern (C) int XIntersectRegion(void *, void *, void *);
extern (C) int XGetZoomHints(void *, size_t, XSizeHints *);
extern (C) int XGetWMSizeHints(void *, size_t, XSizeHints *, int *, size_t);
extern (C) int XGetWMNormalHints(void *, size_t, XSizeHints *, int *);
extern (C) int XGetWMName(void *, size_t, XTextProperty *);
extern (C) int XGetWMIconName(void *, size_t, XTextProperty *);
extern (C) XWMHints * XGetWMHints(void *, size_t);
extern (C) int XGetWMClientMachine(void *, size_t, XTextProperty *);
extern (C) XVisualInfo * XGetVisualInfo(void *, int, XVisualInfo *, int *);
extern (C) int XGetTextProperty(void *, size_t, XTextProperty *, size_t);
extern (C) int XGetStandardColormap(void *, size_t, XStandardColormap *, size_t);
extern (C) int XGetSizeHints(void *, size_t, XSizeHints *, size_t);
extern (C) int XGetRGBColormaps(void *, size_t, XStandardColormap * *, int *, size_t);
extern (C) int XGetNormalHints(void *, size_t, XSizeHints *);
extern (C) int XGetIconSizes(void *, size_t, XIconSize * *, int *);
extern (C) int XGetClassHint(void *, size_t, XClassHint *);
extern (C) int XFindContext(void *, size_t, int, char * *);
extern (C) int XEqualRegion(void *, void *);
extern (C) int XEmptyRegion(void *);
extern (C) int XDestroyRegion(void *);
extern (C) int XDeleteContext(void *, size_t, int);
extern (C) char * XDefaultString();
extern (C) void * XCreateRegion();
extern (C) int XClipBox(void *, XRectangle *);
extern (C) XWMHints * XAllocWMHints();
extern (C) XStandardColormap * XAllocStandardColormap();
extern (C) XSizeHints * XAllocSizeHints();
extern (C) XIconSize * XAllocIconSize();
extern (C) XClassHint * XAllocClassHint();
alias void function(void *, char *, int, int, char * *) _BCD_func__1032;
alias int function(void *) _BCD_func__1074;
alias int function(void *, XErrorEvent *) _BCD_func__1075;
alias void function(void *, char *, char *) _BCD_func__1148;
alias int function(void *, char *, char *) _BCD_func__1149;
alias void function(void *, char *, char *) _BCD_func__1150;
struct XStandardColormap {
size_t colormap;
size_t red_max;
size_t red_mult;
size_t green_max;
size_t green_mult;
size_t blue_max;
size_t blue_mult;
size_t base_pixel;
size_t visualid;
size_t killid;
}
struct XVisualInfo {
Visual * visual;
size_t visualid;
int screen;
int depth;
int c_class;
size_t red_mask;
size_t green_mask;
size_t blue_mask;
int colormap_size;
int bits_per_rgb;
}
struct _XComposeStatus {
char * compose_ptr;
int chars_matched;
}
struct XClassHint {
char * res_name;
char * res_class;
}
struct XIconSize {
int min_width;
int min_height;
int max_width;
int max_height;
int width_inc;
int height_inc;
}
struct XTextProperty {
char * value;
size_t encoding;
int format;
size_t nitems;
}
struct XWMHints {
int flags;
int input;
int initial_state;
size_t icon_pixmap;
size_t icon_window;
int icon_x;
int icon_y;
size_t icon_mask;
size_t window_group;
}
struct N10XSizeHints4__89E {
int x;
int y;
}
struct XSizeHints {
ptrdiff_t flags;
int x;
int y;
int width;
int height;
int min_width;
int min_height;
int max_width;
int max_height;
int width_inc;
int height_inc;
N10XSizeHints4__89E min_aspect;
N10XSizeHints4__89E max_aspect;
int base_width;
int base_height;
int win_gravity;
}
const USPosition      = (1L << 0); /* user specified x, y */
const USSize          = (1L << 1); /* user specified width, height */

const PPosition       = (1L << 2); /* program specified position */
const PSize           = (1L << 3); /* program specified size */
const PMinSize        = (1L << 4); /* program specified minimum size */
const PMaxSize        = (1L << 5); /* program specified maximum size */
const PResizeInc      = (1L << 6); /* program specified resize increments */
const PAspect         = (1L << 7); /* program specified min and max aspect ratios */
const PBaseSize       = (1L << 8); /* program specified base for incrementing */
const PWinGravity     = (1L << 9); /* program specified window gravity */
